apiVersion: v1
kind: Service
metadata:
  name: static-html-nginx
  labels:
    run: static-html-nginx
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  type: LoadBalancer
  selector:
    run: static-html-nginx